---
title: "Digital Dairy Management and Data Analytics"
tbl-colwidths: [5,5,15,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the course. Note that this schedule will be updated as the course progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date | Topic | Teachers | Prepare | Lecture |
|:----------:|:-----------|------------|------------|:----------:|:----------:|
| 1 | 1/20 | Introductory Multiple Choice Questions and Inventory Management | Dr. Hostens and Sumit Sharma | 📖 | 🖥️ |
| 1 | 1/22 | Syllabus Review and Introduction | Dr. Hostens | 📖 | 🖥️ |
| 1 | 1/22 | (LAB) CURC Farm Tour & Presentation from CURC Manager | Dr. Hostens and Sumit Sharma | 📖 | 🖥️ |
| 2 | 1/27 | Principles of Data Collection | Dr. Hostens | 📖 | 🖥️ |
| 2 | 1/29 | Principles of Data Visualization | Dr. Hostens | [📖](https://www.tableau.com/academic/students) | [🖥️](https://prezi.com/view/8Pgr5LLExlIaYtktADox/) |
| 2 | 1/29 | (LAB) Effective visualization using Tableau | Dr. Hostens | [📖](https://github.com/Bovi-analytics/DigitalDairyManagementandDataAnalytics/tree/main/data) | 🖥️ |
| 3 | 2/3 | Understanding Milk Production Data (1) | Meike van Leerdam | 📖 | [🖥️](slides/lec-3.html) |
| 3 | 2/5 | Understanding Milk Production Data (2) | Meike van Leerdam | 📖 | [🖥️](slides/lec-3-2.html) |
| 3 | 2/5 | (LAB) Analyze CURC Milk Production Records | Meike van Leerdam | 📖 | 🖥️ |
| 4 | 2/10 | Cancelled |  | \- | \- |
| 4 | 2/12 | Using Relationships and Joins Between Datasets | Dr. Hostens | [📖](slides/lec-4.html) | [🖥️](https://youtu.be/EpKTHgbu5vQ) |
| 4 | 2/12 | (LAB) Analyze CURC Milk Production Records |  | \- | \- |
| 5 | 2/17 | February break (no class) |  |  |  |
| 5 | 2/19 | CURC Project status discussion | Dr. Hostens |  |  |
| 5 | 2/19 | (LAB) Analyze CURC Milk Production Records | Dr. Hostens |  |  |
| 6 | 2/24 | FAIR data principles for animal science | Dr. Hostens | 📖 | [🖥️](slides/lec-6-1.html) |
| 6 | 2/26 | Inventory Management in Dairy Systems | Dr. Hostens | 📖 | [🖥️](slides/lec-6-2.html) |
| 6 | 2/26 | (LAB) Inventory Calculations | Dr. Hostens |  |  |
| 7 | 3/3 | Integrating Reproductive Management with Farm Systems | Dr. Hostens | 📖 | 🖥️ |
| 7 | 3/5 | No class |  |  |  |
| 7 | 3/5 | (LAB) No Lab |  |  |  |
| 8 | 3/10 | DISC Assessment & Team Dynamics | Dr. Hostens | [📖](weeks/week-8.html) | [🖥️](slides/lec-8.html) |
| 8 | 3/12 | Midterm Prep: CURC Data – Planning Phase I Presentation | Dr. Hostens | 📖 | 🖥️ |
| 8 | 3/12 | (LAB) (LAB) Midterm Presentation Prep: CURC Data Discussion | Dr. Hostens | 📖 | 🖥️ |
| 9 | 3/17 | Midterm Review: CURC Data – Addressing Phase I Questions (Meeting & Presentation with CURC Manager)  | Dr. Hostens | 📖 | 🖥️ |
| 9 | 3/19 | No class |  |  |  |
| 9 | 3/19 | (LAB) No Lab (Dairy Fellows Program) | Dr. Hostens | 📖 | 🖥️ |
| 10 | 3/24 | Handling Uncertainty in Farm Data | Dr. Hostens | 📖 | 🖥️ |
| 10 | 3/26 | CURC Data Discussion – Phase II: Questions from Initial Meeting | Dr. Hostens | 📖 | 🖥️ |
| 10 | 3/26 | (LAB) CURC Data Discussion – Phase II: Addressing Raised Questions | Dr. Hostens | 📖 | 🖥️ |
| 10 | 3/31 | Spring Break (no class) |  |  |  |
| 10 | 4/2 | Spring Break (no class) |  |  |  |
| 11 | 4/7 | Discuss progress questions Matt | Sumit | 📖 | 🖥️ |
| 11 | 4/9 | Discuss progress questions Matt | Dr. Hostens | 📖 | 🖥️ |
| 11 | 4/9 | Lab discussion beef vs dairy semen | Dr. Hostens | 📖 | 🖥️ |
| 12 | 4/14 | No class |  |  |  |
| 12 | 4/16 | Discuss progress questions Matt | Dr. Hostens or TA | 📖 | 🖥️ |
| 12 | 4/16 | Journal club heifer weight | Dr. Hostens | 📖 | 🖥️ |
| 13 | 4/21 | Discuss the dairy business summary 2025 | Dr. Karszes | 📖 | 🖥️ |
| 13 | 4/23 | Benchmark CDREC vs dairy business summary | Dr. Karszes | 📖 | 🖥️ |
| 13 | 4/23 | Economical data deep dive and apply to questions Matt | Dr. Karszes | 📖 | 🖥️ |
| 14 | 4/28 | Monitoring Transition succes through data | Kylie | 📖 | 🖥️ |
| 14 | 4/30 | Practice Presentations (Internal Peer Review) | Dr. Hostens | 📖 | 🖥️ |
| 14 | 4/30 | (LAB) Finalize SWOT & Peer Feedback | Dr. Hostens | 📖 | 🖥️ |
| 15 | 5/5 | Capstone Management Meeting & Course Wrap-Up | Dr. Hostens | 📖 | 🖥️ |
:::

```{r echo = FALSE}
knitr::knit_exit()
```
